A: ,24-07-10 16:55:53,start program
A: ,24-07-10 17:21:43,start program
A: ,24-07-10 17:43:55,start program
A: ,24-07-10 20:16:51,start program
A: ,24-07-11 01:41:36,start program
A: ,24-07-11 02:36:54,start program
A: ,24-07-17 16:07:32,start program
E: ,24-07-17 16:08:39,list index out of range,Traceback (most recent call last):
  File "D:\++\binance-correl\regressionmain.py", line 368, in <module>
    main()
  File "D:\++\binance-correl\regressionmain.py", line 290, in main
    logging_data = logdataset.RegDataSet(
  File "D:\++\binance-correl\logdataset.py", line 64, in __init__
    self.ma_over_1 = ma_over_list[0]
IndexError: list index out of range

A: ,24-07-17 16:09:02,start program
E: ,24-07-17 16:09:39,list index out of range,Traceback (most recent call last):
  File "D:\++\binance-correl\regressionmain.py", line 368, in <module>
    main()
  File "D:\++\binance-correl\regressionmain.py", line 290, in main
    logging_data = logdataset.RegDataSet(
  File "D:\++\binance-correl\logdataset.py", line 64, in __init__
    self.ma_over_1 = ma_over_list[0]
IndexError: list index out of range

A: ,24-07-17 16:17:17,start program
A: ,24-07-17 16:53:11,start program
A: ,24-07-17 16:53:32,start program
A: ,24-07-17 16:57:31,start program
A: ,24-07-17 17:04:00,start program
E: ,24-07-17 17:05:42,'NoneType' object is not iterable,Traceback (most recent call last):
  File "D:\++\binance-correl\regressionmain.py", line 366, in <module>
    main()
  File "D:\++\binance-correl\regressionmain.py", line 111, in main
    top_volume_ticker = [x for x in candle if x["symbol"] in top_volume_symbol]
TypeError: 'NoneType' object is not iterable

A: ,24-07-17 17:07:25,start program
A: ,24-07-17 17:07:34,start program
A: ,24-07-17 17:07:47,start program
A: ,24-07-17 17:08:49,start program
A: ,24-07-17 17:08:57,start program
A: ,24-07-17 17:09:32,start program
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E1DA0EE730>, 'Connection to api.binance.com timed out. (connect timeout=10)'))
R: ,('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
R: ,HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1m&limit=3&symbol=BTCUSDT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F71F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F77F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F77F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DB0C8F7D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
R: ,get_candle() got an unexpected keyword argument 'cl'
A: ,24-11-18 11:56:06,start program
A: ,24-11-18 11:56:37,start program
A: ,24-11-18 12:09:37,start program
A: ,24-11-18 12:12:35,start program
A: ,24-11-18 12:16:15,start program
A: ,24-11-18 12:23:08,start program
A: ,24-11-18 12:29:37,start program
A: ,24-11-18 12:29:49,start program
A: ,24-11-18 12:32:49,start program
A: ,24-11-18 13:49:43,start program
A: ,24-11-18 14:01:45,start program
